# .streamlit/config.toml
[theme]
primaryColor = "#1E3A8A" # Aiclex blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 200 # MB
